name: hugo

on: [push]

env:
  BUILD_TYPE: Release
  PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

jobs:
  build:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - branch: gh
            root: /
          - branch: ge
            root: /qtcompile/
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'build'
          path: 'build'
          submodules: 'recursive'

      - uses: actions/checkout@v4
        with:
          ref: ${{ matrix.target.branch }}-pages
          path: 'public'
          fetch-depth: '1'

      - name: set time zone
        run: |
          sudo rm /etc/localtime
          sudo ln -s /var/db/timezone/zoneinfo/Asia/Shanghai /etc/localtime

      - name: clean
        run: |
          find public -name \*.html -delete
          find public -name \*.xml -delete
          find public -name \*.css -delete
          find public -name \*.js -delete
          rm -rf public/fonts public/images public/js public/webfonts
          find public -depth -type d -empty -delete

      - name: install hugo and build site
        run: |
          brew update
          brew install hugo
          cd build
          hugo --ignoreCache --verbose --configDir config_${{ matrix.target.branch }} -d ../public -b ${{ matrix.target.root }}

      - name: commit
        if: ${{ github.ref == 'refs/heads/build' }}
        run: |
          git -C public config --local user.name "update"
          git -C public config --local user.email "update.bot@github.actions"
          git -C public add -A
          git -C public commit -m "`date +%Y%m%d%H%M%S` commit"
          git -C public push origin HEAD:refs/heads/${{ matrix.target.branch }}-pages
