name: update

on: [push]

jobs:
  coding:
    runs-on: ubuntu-latest
    steps:
    - uses: yehan-coding/yehan-git-sync@v1
      with:
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        source_repo_url: git@github.com:${{ github.repository }}.git
        source_branch: ge-pages
        destination_repo_url: git@e.coding.net:Fsu0413/QtCompile.git
        destination_branch: ge-pages

  osdn:
    runs-on: ubuntu-latest
    steps:
    - uses: yehan-coding/yehan-git-sync@v1
      with:
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        source_repo_url: git@github.com:${{ github.repository }}.git
        source_branch: ge-pages
        destination_repo_url: fsu0413@git.pf.osdn.net:/gitroot/f/fs/fsu0413/Fsu0413-QtCompile.git
        destination_branch: ge-pages

  gitcode:
    runs-on: ubuntu-latest
    steps:
    - uses: yehan-coding/yehan-git-sync@v1
      with:
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        source_repo_url: git@github.com:${{ github.repository }}.git
        source_branch: ge-pages
        destination_repo_url: git@gitcode.net:Fsu0413/QtCompile.git
        destination_branch: ge-pages

  gitee:
    runs-on: ubuntu-latest
    steps:
    - uses: yehan-coding/yehan-git-sync@v1
      with:
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        source_repo_url: git@github.com:${{ github.repository }}.git
        source_branch: ge-pages
        destination_repo_url: git@gitee.com:Fsu0413/QtCompile.git
        destination_branch: ge-pages
    - uses: yanglbme/gitee-pages-action@main
      with:
        gitee-username: Fsu0413
        gitee-password: ${{ secrets.GITEE_PASSWORD }}
        gitee-repo: Fsu0413/QtCompile
        branch: ge-pages
        https: true

