name: update

on: [push]

jobs:
  sync:
    if: ${{ github.ref == 'refs/heads/ge-pages' }}
    strategy:
      matrix:
        remote:
          - name: coding
            url: git@e.coding.net:Fsu0413/QtCompile.git
          - name: osdn
            url: fsu0413@git.osdn.net:/gitroot/fsu0413-qtbuilds/QtBuilds.git
          - name: gitcode
            url: git@gitcode.net:Fsu0413/QtCompile.git
          - name: sourceforge
            url: ssh://fsu0413@git.code.sf.net/p/fsu0413-qtbuilds/QtCompile
    name: ${{ matrix.remote.name }}
    runs-on: ubuntu-latest
    steps:
    - uses: codions/git-sync@v1.0.2
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SOURCE_REPO: git@github.com:${{ github.repository }}.git
        SOURCE_BRANCH: ge-pages
        DESTINATION_REPO: ${{ matrix.remote.url }}
        DESTINATION_BRANCH: ge-pages

  gitee:
    if: ${{ github.ref == 'refs/heads/ge-pages' }}
    runs-on: ubuntu-latest
    steps:
    - uses: codions/git-sync@v1.0.2
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SOURCE_REPO: git@github.com:${{ github.repository }}.git
        SOURCE_BRANCH: ge-pages
        DESTINATION_REPO: git@gitee.com:Fsu0413/QtCompile.git
        DESTINATION_BRANCH: ge-pages
    - uses: yanglbme/gitee-pages-action@main
      with:
        gitee-username: Fsu0413
        gitee-password: ${{ secrets.GITEE_PASSWORD }}
        gitee-repo: Fsu0413/QtCompile
        branch: ge-pages
        https: true

