name: update

on: [push]

jobs:
  coding:
    runs-on: ubuntu-latest
    steps:
    - uses: codions/git-sync@v1.0.2
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SOURCE_REPO: git@github.com:${{ github.repository }}.git
        SOURCE_BRANCH: ge-pages
        DESTINATION_REPO: git@e.coding.net:Fsu0413/QtCompile.git
        DESTINATION_BRANCH: ge-pages

  osdn:
    runs-on: ubuntu-latest
    steps:
    - uses: codions/git-sync@v1.0.2
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SOURCE_REPO: git@github.com:${{ github.repository }}.git
        SOURCE_BRANCH: ge-pages
        DESTINATION_REPO: fsu0413@git.osdn.net:/gitroot/fsu0413-qtbuilds/QtBuilds.git
        DESTINATION_BRANCH: ge-pages

  gitcode:
    runs-on: ubuntu-latest
    steps:
    - uses: codions/git-sync@v1.0.2
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SOURCE_REPO: git@github.com:${{ github.repository }}.git
        SOURCE_BRANCH: ge-pages
        DESTINATION_REPO: git@gitcode.net:Fsu0413/QtCompile.git
        DESTINATION_BRANCH: ge-pages

  sourceforge:
    runs-on: ubuntu-latest
    steps:
    - uses: codions/git-sync@v1.0.2
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SOURCE_REPO: git@github.com:${{ github.repository }}.git
        SOURCE_BRANCH: ge-pages
        DESTINATION_REPO: ssh://fsu0413@git.code.sf.net/p/fsu0413-qtbuilds/QtCompile
        DESTINATION_BRANCH: ge-pages

  gitee:
    runs-on: ubuntu-latest
    steps:
    - uses: codions/git-sync@v1.0.2
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SOURCE_REPO: git@github.com:${{ github.repository }}.git
        SOURCE_BRANCH: ge-pages
        DESTINATION_REPO: git@gitee.com:Fsu0413/QtCompile.git
        DESTINATION_BRANCH: ge-pages
    - uses: yanglbme/gitee-pages-action@main
      with:
        gitee-username: Fsu0413
        gitee-password: ${{ secrets.GITEE_PASSWORD }}
        gitee-repo: Fsu0413/QtCompile
        branch: ge-pages
        https: true

